import { readFileSync, writeFileSync } from 'node:fs';

const runs = [1, 2, 3, 4, 5].map((i) => {
  const lines = readFileSync(`/tmp/perf-run-${i}.txt`, 'utf8').trim().split('\n');
  const map = new Map();
  for (const line of lines) {
    const m = line.match(/^\[perf\] ([^:]+): ([\d.]+)(?:ms)?$/);
    if (!m) continue;
    map.set(m[1], parseFloat(m[2]));
  }
  return map;
});

const labels = [...new Set(runs.flatMap((m) => [...m.keys()]))];

const results = {};
for (const label of labels) {
  const samples = runs.map((m) => m.get(label)).filter((v) => v !== undefined);
  if (samples.length === 0) continue;
  samples.sort((a, b) => a - b);
  const min = samples[0];
  const max = samples[samples.length - 1];
  const median = samples[Math.floor(samples.length / 2)];
  const mean = samples.reduce((s, v) => s + v, 0) / samples.length;
  results[label] = {
    samples,
    min: Math.round(min * 100) / 100,
    median: Math.round(median * 100) / 100,
    mean: Math.round(mean * 100) / 100,
    max: Math.round(max * 100) / 100,
  };
}

const baseline = {
  capturedAt: new Date().toISOString(),
  runs: 5,
  node: process.version,
  platform: process.platform,
  arch: process.arch,
  unit: 'ms (except selector/subscribe counters which are dimensionless)',
  notes: 'Generated by aggregating `[perf]` lines from 5 sequential `npm run test:perf` runs. Use `median` as the headline number; `min` shows best-case after warmup, `max` hints at noise.',
  benchmarks: results,
};

writeFileSync(
  '/Volumes/WD_BLACK/GitHub/sketchy/perf-baseline/baseline.json',
  JSON.stringify(baseline, null, 2) + '\n',
);

console.log(`Wrote ${labels.length} benchmarks to perf-baseline/baseline.json`);
console.log('\nTop 10 slowest (by median):');
const sorted = Object.entries(results).sort((a, b) => b[1].median - a[1].median);
for (const [label, r] of sorted.slice(0, 10)) {
  console.log(`  ${label.padEnd(45)} median=${String(r.median).padStart(9)}  [${r.min} .. ${r.max}]`);
}
